[theme]
primaryColor="#1e88e5"  # A bright blue for primary elements
backgroundColor="#121212" # Dark background
secondaryBackgroundColor="#2a2a2a" # Slightly lighter dark for secondary backgrounds
textColor="#e0e0e0" # Light gray text
font="serif"